name: CI para Spring Boot

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.repository_owner }}/devopstoolsis

jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write

   steps:
     - name: Clonar el repositorio
       uses: actions/checkout@v3

     - name: Configurar Java
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: Compila, prueba y empaqueta
       run: mvn -B package --file pom.xml

 build-and-push-docker:
   needs: build
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
    
   steps:
     - uses: actions/checkout@v4
    
     - name: Log in a GitHub Container Registry
       uses: docker/login-action@v3
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
        
     - name: Extraer metadatos (tags, labels) para Docker
       id: meta
       uses: docker/metadata-action@v5
       with:
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=latest
           type=raw,value={{version}}
           type=sha,format=short
        
     - name: Build y push de la imagen de Docker
       uses: docker/build-push-action@v5
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}

